CREATE TABLE IF NOT EXISTS paper_trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TEXT NOT NULL,
  symbol TEXT NOT NULL,
  action TEXT NOT NULL,
  quantity DOUBLE PRECISION NOT NULL,
  entry_price DOUBLE PRECISION NOT NULL,
  stop_loss DOUBLE PRECISION NOT NULL,
  take_profit DOUBLE PRECISION NOT NULL,
  status TEXT DEFAULT 'OPEN',
  close_price DOUBLE PRECISION,
  pnl DOUBLE PRECISION,
  fee_approx DOUBLE PRECISION,
  rejection_reason TEXT,
  ai_confidence DOUBLE PRECISION,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS paper_account (
  id BIGINT PRIMARY KEY,
  balance DOUBLE PRECISION NOT NULL,
  equity DOUBLE PRECISION NOT NULL,
  daily_loss DOUBLE PRECISION NOT NULL DEFAULT 0,
  last_reset_date TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS system_state (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

ALTER TABLE paper_trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE paper_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_state ENABLE ROW LEVEL SECURITY;

-- Server routes use the service role key and bypass RLS. Do not expose the service role key in client code.
